IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-04-09 18:52:27 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/16132479", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-04-09 18:52:27 UTC}, issueCommentBody = "I assumed you needed _setuptools_ to execute _2to3_ with _setup.py_, but found out there is a trick with pythons standard _distutils_[1]. Last commit implements this. For python2.5 compatibility and python3.x, I had to change `print` statements to `sys.stdout.write`, which works a treat :smile:\r\n\r\nArguably _fail2ban-2to3_ is redundant but it's useful for testing currently, so I've left it for now. \r\n\r\n@yarikoptic If you like, I can merge this with 0.9 branch, close this pull request and open a new one against 0.9 branch. I believe there are a fair few conflicts (I'll also wait for the fail2ban module pull request to be merged 0.9 before doing this).\r\n\r\n[1]: http://wiki.python.org/moin/PortingPythonToPy3k", issueCommentId = 16132479}