IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-02-26 15:57:58 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/e5215f0bc7dc90e3ba544ceedb895cd0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "alick9188", githubOwnerUrl = "https://api.github.com/users/alick9188", githubOwnerId = 933935, githubOwnerGravatarId = "e5215f0bc7dc90e3ba544ceedb895cd0"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/14122130", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-02-26 15:57:58 UTC}, issueCommentBody = "Any update for this issue? I've met it on Fedora 18 now.", issueCommentId = 14122130}