IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-24 20:19:37 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15368313", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-24 20:19:37 UTC}, issueCommentBody = "@Glandos Travis CI can sometimes fail on tests where pyinotify doesn't react in time, which is annoying. Usually safe to ignore failure of the testcases if it's just `MonitorFailures`. #103 is looking at this.", issueCommentId = 15368313}