IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-24 16:40:39 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/f49f984a790556065284c1ac5b664c2b?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "Glandos", githubOwnerUrl = "https://api.github.com/users/Glandos", githubOwnerId = 297578, githubOwnerGravatarId = "f49f984a790556065284c1ac5b664c2b"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15362266", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-24 16:40:39 UTC}, issueCommentBody = "And I took the log of travis, run it line by line on my machine, on still no errors, with exactly the same version of software, except pip (I've got 1.1 and travis has 1.3.1).", issueCommentId = 15362266}