IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-24 15:12:44 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15360482", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-24 15:12:44 UTC}, issueCommentBody = "The use of `as` with the `except` statement is only compatible with python2.6+. Switching to `,` syntax should maintain compatibility with python2.4+ [1].\r\n\r\n[1]: http://docs.python.org/2.4/ref/try.html", issueCommentId = 15360482}