IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2012-08-03 17:23:36 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/68d806db1b31ae8e9464b583e2aa29c6?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "afragen", githubOwnerUrl = "https://api.github.com/users/afragen", githubOwnerId = 1296790, githubOwnerGravatarId = "68d806db1b31ae8e9464b583e2aa29c6"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/7488880", issueCommentCreatedAt = GithubDate {fromGithubDate = 2012-08-03 17:23:36 UTC}, issueCommentBody = "I did a reinstall of 0.8.7.1 and now don't see the error. Will continue to monitor re: actionunban", issueCommentId = 7488880}