[Repo {repoSshUrl = "git@github.com:ajhoughton/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2012-11-08 10:56:59 UTC}, repoHtmlUrl = "https://github.com/ajhoughton/fail2ban", repoSvnUrl = "https://github.com/ajhoughton/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/ajhoughton/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/ajhoughton/fail2ban.git", repoSize = 136, repoUpdatedAt = GithubDate {fromGithubDate = 2012-11-08 11:08:39 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/4481fa93eb8710047ed4e11a3ac533c8?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "ajhoughton", githubOwnerUrl = "https://api.github.com/users/ajhoughton", githubOwnerId = 2750072, githubOwnerGravatarId = "4481fa93eb8710047ed4e11a3ac533c8"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Nothing, repoPushedAt = Just (GithubDate {fromGithubDate = 2012-11-08 11:08:37 UTC}), repoId = 6595042, repoUrl = "https://api.github.com/repos/ajhoughton/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}]