Repo {repoSshUrl = "git@github.com:Th4nat0s/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2012-06-08 18:01:41 UTC}, repoHtmlUrl = "https://github.com/Th4nat0s/fail2ban", repoSvnUrl = "https://github.com/Th4nat0s/fail2ban", repoForks = 1, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/Th4nat0s/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/Th4nat0s/fail2ban.git", repoSize = 152, repoUpdatedAt = GithubDate {fromGithubDate = 2012-11-08 21:23:40 UTC}, repoWatchers = 1, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/78225da31896e34ca3196c46fae08bf4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "Th4nat0s", githubOwnerUrl = "https://api.github.com/users/Th4nat0s", githubOwnerId = 1728186, githubOwnerGravatarId = "78225da31896e34ca3196c46fae08bf4"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2012-11-08 21:23:39 UTC}), repoId = 4600476, repoUrl = "https://api.github.com/repos/Th4nat0s/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}