IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 21:27:17 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/12721691", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-01-25 21:27:17 UTC}, issueCommentBody = "@bluephoenix47 That doesn't seem right. Checking the [PKGBUILD for systemd](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/systemd#n38), it appears that build config sets python to python2. Maybe try updating or reinstalling systemd.\r\n\r\nI'd also try installing python2-systemd straight from AUR.", issueCommentId = 12721691}