Repo {repoSshUrl = "git@github.com:fail2ban/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2011-09-28 16:24:20 UTC}, repoHtmlUrl = "https://github.com/fail2ban/fail2ban", repoSvnUrl = "https://github.com/fail2ban/fail2ban", repoForks = 39, repoHomepage = Just "http://www.fail2ban.org", repoFork = False, repoGitUrl = "git://github.com/fail2ban/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/fail2ban/fail2ban.git", repoSize = 2171, repoUpdatedAt = GithubDate {fromGithubDate = 2012-12-29 16:34:29 UTC}, repoWatchers = 176, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/8b9fae091db6d1c53a06a3dfb05e097d?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", githubOwnerLogin = "fail2ban", githubOwnerUrl = "https://api.github.com/users/fail2ban", githubOwnerId = 1087378, githubOwnerGravatarId = "8b9fae091db6d1c53a06a3dfb05e097d"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2012-12-24 18:18:04 UTC}), repoId = 2476162, repoUrl = "https://api.github.com/repos/fail2ban/fail2ban", repoOpenIssues = 35, repoHasWiki = Just False, repoHasIssues = Just True, repoHasDownloads = Just True}